language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- npm install
branches:
  only:
  - master
script:
- travis_wait 30 python api.py
env:
  global:
  - GIT_COMMITTER_NAME=Mirucon
  - GIT_COMMITTER_EMAIL=i@miruc.co
  - GIT_AUTHOR_NAME=Mirucon
  - GIT_AUTHOR_EMAIL=i@miruc.co
  - secure: "K/hCYwtAJBFF/qew+MAiNRj+K0pvoXHXgTSbSAsj3sRzE1TmgoUvwvk/lOSFRxDiPCGx99+yX/Wf5G8/xaXpLgH4S4FknZPdOV4ozdYagqM9e9X3wOmBiv1qVgBJDPNKIN/FFeVEl22l5ml9PhckZYidIBVc6M8lwtumS8cotGLX/nr4rsF1fyWXQ3DBRSNwIElJdVC3umYVIVdd3/gXEp9mJbxIvmGcrUa+nbobSBlYDnA8TqNdDtf8qVpZJPStbJqsz8nL50X7FA52xu3lFIzH7CXfZUYoQHCAkpRbMPfzcBwGYH81LHMTKS2yqAuO3zllHaj3QnLoTGxEhJpOrjuhzx5G2ylaFpvrJl8oIGDkXaq1ysx+UzmL6O54AacWwhJDNZeItOGWcZSVt4PXo3B69gNsdKJfh025quhRT3On0ll+exuV+cux0tLS4upU0claUWlc0ET6abpj7Om5GZ7HR2LqoZoTMenWpQ7KDfyXT3M1z+1tFes49EOLFWfN6Uw4Ud36CWlCauA/0yKz1sQPHfplSJU6x1r08uWSfUuSccRIeTYx+a8GbSiSdvtkKNX7RWXdGxCAVOGaq0j8Efy62HSJqq26zOVya4WWlhS8Xe+mbmzsmMERtY/GDRLc0EJF5+n/dN5JBVJRDN2cXIR2ippMQFeIy4/BctHfHGU="
after_success:
- bash ./bin/deploy.sh
notifications:
  slack:
    secure: XxMrKjp3n1R0wAGq7V+5ppbtBnrGdhBZ0GMG9yp9Fm4330rD0l1IPePdY8fUioreJ5KLMEJuIHU5jud/99Qa1cjjV3Trn9IRFs5rBDNHz52XShECLvfaP/M2VA+rgGKTHeGNJM0Oxa7Yck3Qf1hKNCI/pJ/tVHHrcp8ohyhTodpYFunTUJp79BzSWrFTfcvBcEXMPxd5gwJK1S1TA/33ArDRjpTtBUNrbdPskUhqE3tG+WJCn5/8i6CBQiI8BbZ/+tE1PC7RUg/RLvvrNEs8JnbaDkafghSwfcB6rgFljbOXwg2O8A1ug/755ux8EdAqrr/2FDhOdPaCKu9TbBbCjKEKcv7xrJCzyAqT4KX4jnKAqnNN9X/bNY/F7sf5iMg4R+PDaen3v1hj5MOYEA0qQarcOw2D3jMOWCFjZzc9U776tJijH4m+hcjxqiJawfBOJnLqPYS3xvJ6H7PXrLctPZH2wdIk2L1rOYym6+K4uA9p3rVf11DPp+hQA8FWXUgTuv4bzYzcUz1hCZhSi6VuC76wl149uwqCTm1H5YzoJPHnZM425C/atzEkEyl/xamOFNdKQP564aWLGNgkT5us6EGCV3ON+vhfrml1md5Szrf8IfWKRRLW3IrtH/gwWEC3biBkFzb22tHXDOMvmsX3j0I1GnQVI7ZvEM6D5k/HMXw=
    on_success: always
