language: python

python:
  - "3.6"

before_install:
  - openssl aes-256-cbc -K $encrypted_06c76a5b5a4d_key -iv $encrypted_06c76a5b5a4d_iv -in github_travis.enc -out github_travis -d

install:
  - pip install -r requirements.txt
  - npm install

branches:
  only:
    - master

script:
  - travis_wait python api.py

env:
  global:
    - GIT_COMMITTER_NAME=Mirucon
    - GIT_COMMITTER_EMAIL=i@miruc.co
    - GIT_AUTHOR_NAME=Mirucon
    - GIT_AUTHOR_EMAIL=i@miruc.co

after_success:
  # Run build task.
  - bash ./bin/deploy.sh